version: "3"

networks:
  app-tier:
    driver: bridge

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app-tier

  my-release-kafka:
    image: 'bitnami/kafka:latest'
    ports:
      # Maps the external port to outside of the docker env, this helps test the aplication
      # without needing to enter the docker env.
      - '9093:9093'

    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://my-release-kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
    networks:
      - app-tier

  clickhouse-server:
    image: 'event-clickhouse'
    ports:
      - '19000:9000'
      - '18123:8123'
    #environment:
    #  - CLICKHOUSE_USER=user_reader
    #  - CLICKHOUSE_PASSWORD=123
    #  - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    depends_on:
      - my-release-kafka
    networks:
      - app-tier

  myapp:
    image: 'kafkapython'
    ports:
      - '8080:80'
    networks:
      - app-tier
    depends_on:
      - clickhouse-server


